#!/usr/bin/env bash
echo "== put-object"

# Check for bucket  name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg"
    exit 1
fi

if [ -z "$2" ]; then
    echo "There needs to be a bucket name eg"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

aws s3api put-object --bucket $BUCKET_NAME \
--body $FILENAME