#!/usr/bin/env bash
echo "== sync"

# Exit immediately if any command returns a non-zero status
set -e

# Where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"
# remove folder if it already exists
rm -r $OUTPUT_DIR

# Let's create output folder
mkdir -p "$OUTPUT_DIR"

# Generate a random number (between 5 and 10)
NUM_FILES=$((RANDOM % 6 + 5))

echo "Generating $NUM_FILES random files..."

for ((i=1; i<=NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"

    # Generate random data and write it to the file (size between 1KB and 100KB)
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 100 + 1)) 2>/dev/null

    echo "Created $FILENAME"
done

tree $OUTPUT_DIR

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files